# Generated by Django 6.0.3 on 2026-04-03 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=155)),
                ('status', models.CharField(choices=[('active', 'Acvite'), ('inactive', 'Inactive')], max_length=155)),
                ('joined_at', models.TimeField(auto_now=True)),
                ('left_at', models.TimeField(blank=True, null=True)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_member',
            },
        ),
    ]
