# Generated by Django 6.0.3 on 2026-04-04 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_description_workspace_owner'),
        ('workspace_member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.RemoveField(
        model_name='workspacemember',
        name='added_at',
    ),
    migrations.RemoveField(
        model_name='workspacemember',
        name='joined_at',
    ),
    migrations.AddField(
        model_name='workspacemember',
        name='joined_at',
        field=models.DateTimeField(auto_now_add=True),
    ),
    migrations.RemoveField(
        model_name='workspacemember',
        name='left_at',
    ),
    migrations.AddField(
        model_name='workspacemember',
        name='left_at',
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AlterField(
        model_name='workspacemember',
        name='member',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
    ),
    migrations.AlterField(
        model_name='workspacemember',
        name='role',
        field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=50),
    ),
    migrations.AlterField(
        model_name='workspacemember',
        name='status',
        field=models.CharField(choices=[('active', 'Acvite'), ('inactive', 'Inactive')], max_length=50),
    ),
    migrations.AlterField(
        model_name='workspacemember',
        name='workspace',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace'),
    ),
]