# Generated by Django 6.0.3 on 2026-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
